# Generated by Django 2.2.7 on 2020-09-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_auto_20200914_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissionid',
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='online.Permission'),
        ),
    ]
