# Generated by Django 2.2.7 on 2020-09-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_auto_20200915_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='wenjianxiyuan',
            new_name='jiqunchakan',
        ),
        migrations.AddField(
            model_name='permission',
            name='moxingsuanfa',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='permission',
            name='wenjianziyuan',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
