# Generated by Django 2.0 on 2019-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_soure', models.CharField(max_length=50)),
                ('class1', models.CharField(max_length=50)),
                ('class2', models.CharField(max_length=50)),
                ('class3', models.CharField(max_length=50)),
                ('class4', models.CharField(max_length=50)),
                ('time_year', models.CharField(max_length=50)),
                ('time_month', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=80)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
