# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0005_file_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_record',
            name='file_path',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
