# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0006_file_record_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_record',
            name='content_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file_record',
            name='file_type',
            field=models.CharField(max_length=30),
        ),
    ]
