# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0007_auto_20180618_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file_record',
            options={'verbose_name_plural': '\u4e0a\u4f20\u6587\u4ef6\u8bb0\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name_plural': '\u7528\u6237\u64cd\u4f5c'},
        ),
        migrations.RenameField(
            model_name='file_record',
            old_name='introduce',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='file_record',
            old_name='content_type',
            new_name='data_name',
        ),
        migrations.RenameField(
            model_name='file_record',
            old_name='file_type',
            new_name='data_source',
        ),
        migrations.RenameField(
            model_name='file_record',
            old_name='username',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='file_record',
            name='important',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='file_record',
            name='place',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='file_record',
            name='time',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
