# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0008_auto_20180719_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='function_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('function_type', models.CharField(max_length=200)),
                ('upload_user', models.CharField(max_length=200)),
                ('input_files_path', models.CharField(max_length=200)),
                ('output_files_path', models.CharField(max_length=200)),
                ('parameter', models.CharField(max_length=200)),
                ('introduce', models.CharField(max_length=50000)),
            ],
            options={
                'verbose_name_plural': '\u5927\u6570\u636e\u65b9\u6cd5',
            },
        ),
    ]
