# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0009_function_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_model',
            name='file_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
