# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0010_function_model_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='mypicture', verbose_name='\u56fe\u7247')),
            ],
        ),
    ]
