# Generated by Django 2.0 on 2019-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0011_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_model',
            name='function_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
