# Generated by Django 2.0 on 2019-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0012_auto_20191203_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='function_model',
            name='function_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='function_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='input_files_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='introduce',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='output_files_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='parameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='function_model',
            name='upload_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
